---
namespace: sol1-ansible
name: receptor
version: 1.0.1
readme: README.md
authors:
  - Sol1
description: Receptor installer
license_file: LICENSE
tags:
  - networking
  - infrastructure
  - receptor
repository: https://github.com/sol1-ansible/sol1-receptor-collection
