---
receptor_user: receptor
receptor_group: receptor

receptor_config_path: '/etc/receptor'
receptor_socket_dir: '/var/run/receptor'
receptor_control_filename: 'receptor.sock'

receptor_tls: false
receptor_mintls13: false

receptor_tls_dir: "/etc/receptor/tls"
receptor_tls_ca_dir: "{{ receptor_tls_dir }}/ca"
receptor_tls_crt: ""
receptor_tls_key: ""
receptor_ca_crt: ""
receptor_ca_key: ""

receptor_worksign_private_key: ""
receptor_worksign_public_key: ""

receptor_fd_limit_soft: 4096
receptor_fd_limit_hard: 8192

receptor_listener: true
receptor_local_only: false

receptor_protocol: 'tcp'
receptor_port: 27199
receptor_sign: false
receptor_verify: false

receptor_log_level: 'info'

_hostname: "{{ routable_hostname | default(ansible_host) }}"
receptor_host_identifier: "{{ (_hostname == 'localhost') | ternary('localhost.localdomain', _hostname) }}"
