---

- name: Create Receptor cert directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: '0750'
    owner: "{{ receptor_user }}"
    group: "{{ receptor_group }}"
    recurse: true
  with_items:
    - "{{ receptor_tls_dir }}"
    - "{{ receptor_tls_ca_dir }}"

- name: Debug - template certs next
  ansible.builtin.debug:
    msg: "About to template the tls certs"

- name: Install provided TLS certs and keys
  ansible.builtin.template:
    src: "{{ config.src }}"
    dest: "{{ config.dst }}"
    mode: "{{ config.mode | default('00640') }}"
    owner: "{{ config.owner | default(receptor_user) }}"
    group: "{{ config.group | default(receptor_group) }}"
  loop:
    - { src: receptor.crt.j2, dst: "{{ receptor_tls_dir }}/receptor.crt" }
    - { src: receptor.key.j2, dst: "{{ receptor_tls_dir }}/receptor.key", mode: "00600" }
    - { src: receptor-ca.crt.j2, dst: "{{ receptor_tls_dir }}/ca/receptor-ca.crt" }
    - { src: receptor-ca.key.j2, dst: "{{ receptor_tls_dir }}/ca/receptor-ca.key", mode: "00600" }
  loop_control:
    loop_var: config
  no_log: "{{ awx_no_log }}"
